### PR TITLE
Update dependencies (Add css variable for custom font)

### PR DESCRIPTION
**Pull request by lcfd**

### CODE REVIEW

**Comment by Piiit** [comment]
@fedriz Thx

**Comment by Piiit** [comment]
@fedriz We do not have fonts in this widget, right? Or do I miss some information here?

**Comment by lcfd** [comment]
@Piiit Yes, it's true but I've used the opportunity to update the dependencies

**Comment by Piiit** [comment]
Top... Thanks

On Jul 1, 2020 09:17, Luca Fedrizzi <notifications@github.com> wrote:

@Piiit<https://github.com/Piiit> Yes, it's true but I took the opportunity to update the dependencies

**Pull request merged**
